"""added client data to widget data corrected error

Revision ID: 1fc4ef13ac3f
Revises: 2ab2725a01bf
Create Date: 2023-04-10 19:10:18.780351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc4ef13ac3f'
down_revision = '2ab2725a01bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
